### ISSUE TITLE
Error Tipográfico en Tema 0 - Transparencia 15 

### ISSUE THREAD

**Issue by brian8sal** [LatacitaTeaching/IngenieriaRequisitos#19]
En el ítem 1 falta el punto final que el resto tienen.

Creo que sería conveniente añadirlo, para que la estructura sea la misma que la del resto.

**Comment by latacita** [comment]
La petición ha sido procesado y la solicitud atendida.

Por favor, comprueba que esté solucionada antes de cerrarla.
