### ISSUE TITLE
Error ortográfico  en tema 1 - Transparencia 13 (26 de 47)

### ISSUE THREAD

**Issue by Victor98PA** [LatacitaTeaching/IngenieriaRequisitos#20]
Error en la palabra FUNCIONAMIENTO en la definición de encarnación.

**Comment by latacita** [comment]
Gracias por el aviso. 

Para futuras solicitudes, indica número de tema y transparencia donde aparece el error.

**Comment by latacita** [comment]
Confirma que está resuelta y si es así cierro la petición.

**Comment by Victor98PA** [comment]
Peticion resuelta.
