### ISSUE TITLE
Errata Tema 2 Diapositiva 69

### ISSUE THREAD

**Issue by brian8sal** [LatacitaTeaching/IngenieriaRequisitos#21]
Hay una errata en el Tema 2, en la diapositiva 69. Falta un espacio entre las palabras "stakeholder" y "el" en el punto 1 de Ejecución. No dificulta la comprensión de la presentación, pero sería conveniente subsanarlo.

Gracias.

**Comment by latacita** [comment]
Admitida. 

El fallo se corregirá junto con otros en la siguiente versión de las transparencias, que se subirán a moodle una vez concluido el Tema 2, para no desincronizar las transparencias de los itinerarios.

**Comment by latacita** [comment]
Pendiente de verificación en moodle.

**Comment by latacita** [comment]
Detectado un nuevo error, stakeholders aparece en singular cuando debería ser plural.

Se sugiere cambiarlo.

**Comment by latacita** [comment]
Verificar cambio en moodle.

**Comment by latacita** [comment]
Verificado.
