### ISSUE TITLE
Erratas en el caso de estudio (Gestor de Planes de Convalidación)

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#23]
Buenas,

he detectado las tres siguientes posibles erratas en este caso de estudio. 

- En el segundo párrafo de la página falta un "de" en la fragmento siguiente:
   "para la gestión de los expedientes (de) alumnos de intercambio"

- En el sexto punto de la enumeración falta un espacio de separación entre dos palabras:
   " un plan de convalidaciones ( ) de manera..."

- En el segundo párrafo contando a partir de la enumeración aparece la palabra "costaría" cuando creo que la palabra adecuada sería "constaría".

Un saludo

**Comment by latacita** [comment]
Constatados los errores y admitida la incidencias.

**Comment by latacita** [comment]
Arreglado. 

Comprueba que esté todo correcto y cierro la incidencia.

**Comment by erl430** [comment]
Todo correcto
