### ISSUE TITLE
Problema con el vídeo introductorio del tema 2

### ISSUE THREAD

**Issue by rukalrey** [LatacitaTeaching/IngenieriaRequisitos#24]
Al iniciar la reproducción del vídeo, no se inicia y pone un mensaje de que el autor, ha deshabilitado el vídeo. No se si hay que subirlo aquí o si es un error, porque igual es que simplemente todavía no le has subido.

**Comment by latacita** [comment]
Admitida. 

Se solucionará en breve.

**Comment by latacita** [comment]
Comprueba que esté solucionado, y dime cuál es tu nombre para poder darte un punto en notificación de errores.

**Comment by rukalrey** [comment]
En principio me sigue pasando lo mismo, Rubén Calleja Reigadas.

**Comment by latacita** [comment]
Mándame una captura de lo que te sale.

**Comment by rukalrey** [comment]
![image](https://user-images.githubusercontent.com/60737931/74108656-d7657580-4b7c-11ea-9a3b-5c9e72e77590.png)

**Comment by latacita** [comment]
Se ha cambiado una opción en configuración de YouTube. Prueba de nuevo.

**Comment by rukalrey** [comment]
Ahora ya esta bien,  gracias
