### ISSUE TITLE
Erratas - Competencias transversales (Pacto de equipo)

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#25]
Buenas,

he encontrado las siguientes posibles erratas en la página que introduce los pactos de equipo:

- En el primer párrafo aparece "la exigibilidad individual la interacción positiva." y entiendo que pueda faltar una "y" entre ambos conceptos.

- En el sexto párrafo aparece "no todas los estudiantes" cuando entiendo que lo correcto sería "todos".

- En el séptimo párrafo aparece "todo ellos generará" donde entiendo que sobra la s de ellos.

- En el primer párrafo de la parte de pactos de equipo aparece "equipos autogestionados y autoorganizados suelen ser más eficientes", donde entiendo que sería "eficiente".

- En la parte de expulsión de un estudiante de un equipo, en el último párrafo aparece "el alumno se regirá por un procedimiento de evaluación alternativo la ordinario", cuando entiendo que sería "al" en vez de "la".

Un saludo.

**Comment by latacita** [comment]
Admitida todas. Gracias por tomarte la molestia en reportar los errores.

**Comment by latacita** [comment]
Arreglado.

Por favor, confirma que todo esté correcto.

**Comment by erl430** [comment]
Todo correcto
