### ISSUE TITLE
Errata - Caso de uso Reading Manager

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#27]
Buenas, 

en el primer párrafo aparece "la realización de todas lecturas" cuando entiendo que sería "la realización de todas *las* lecturas".

Un saludo

**Comment by latacita** [comment]
Admitida.

**Comment by latacita** [comment]
Corregida. 

Verifica que esté correcta para poder cerrar la incidencia.

**Comment by erl430** [comment]
Todo correcto
