### ISSUE TITLE
Erratas - Diapositivas Tema 1

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#28]
Buenas,

en las diapositivas del tema 1 he encontrado las siguientes erratas:

- en la diapositiva 13, en la definición de requisito de producto aparece "producto sw a ser desarrollada", donde entiendo que debería poner "desarrollado"

- también en la diapositiva 13, en la definición de requisito de proceso, creo que se ha omitido el artículo "el" en la frase siguiente "exhibir el proceso utilizado para (el) desarrollo de un cierto sistema software"

- en la diapositiva 20, en la definición de objetivo, aparece "un objetivo de un sistema software es una fin", donde entiendo que debería poner "un"

Un saludo

**Comment by latacita** [comment]
Admitida. 

Muchas gracias por el esfuerzo y ls notificaciones.

**Comment by latacita** [comment]
Por favor, verifica que esté todo correcto y responde a este comentario.

**Comment by erl430** [comment]
Todo correcto
