### ISSUE TITLE
Itinerario Tema 2

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#30]
Buenas,

en las tareas 18, 19, 20, 21, 22 y 23 del itinerario del Tema 2 no aparece el número de la lectura a la que se corresponden.

Un saludo

**Comment by latacita** [comment]
Admitida

**Comment by latacita** [comment]
Solucionado. 

Verifica que esté todo correcto.

**Comment by erl430** [comment]
Todo correcto
