### ISSUE TITLE
Entrega documento Vision

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#31]
Buenas,

No se si esto se notifica aquí, pero la fecha de entrega del documento de la definición de la visión está desactualizada (será la del año pasado), y creo recordar que es para mañana jueves. Aunque nos deja agregar la entrega, me gustaría comprobar que la fecha de entrega es mañana.

Un saludo

**Comment by latacita** [comment]
Admitida. 

Sí, se notifica por aquí.

**Comment by latacita** [comment]
Verifica que esté arreglado.

**Comment by erl430** [comment]
Todo correcto
