### ISSUE TITLE
Erratas - Fase 3: Identificación de las fuentes de requisitos

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#32]
Buenas, 

he encontrado las siguientes posibles erratas:
- En el título, aparece "identificación de la(s) fuente de requisitos", donde entiendo que falta una s.
- En el primer párrafo aparece la palabra "identifición" donde entiendo que es "identificación".
- En el último párrafo de la introducción aparece "que se detallan en al siguiente sección", donde supongo que sería "la".
- En el apartado de Descripción de las fuentes, en el punto 1 aparece "asignador", cuando entiendo que es "asignado".
- En el punto 4, al final de la línea aparece ".make".

Un saludo

**Comment by latacita** [comment]
Admitidas todas. 

Muchas gracias.

**Comment by latacita** [comment]
Arreglado. 

Verifica que esté todo correcto, por favor.

**Comment by erl430** [comment]
Todo correcto.
