### ISSUE TITLE
Erratas Fase 4 - Selección de estrategias para la Captura de Requisitos

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#34]
Buenas,

en la página de la fase 4 del proyecto he encontrado las siguientes erratas:

En el apartado de la introducción:
- En el último párrafo de la introducción, aparece un " º " que entiendo que no tiene sentido.
- En ese mismo párrafo aparece "deberá satisfacerse los objetivos", cuando entiendo que sería "deberán satisfacerse los objetivos".

En el apartado de objetivos:
- En la primera línea aparece "los objetivos concreto", cuando entiendo que sería "concretos".
- En el punto número uno, falta un espacio en "requisitos () que". Además, justo después aparece "rslte más adecuada", cuando entiendo que sería "resulte".
- En el punto tres aparece "ser capaz a secuenciar", cuando entiendo que sería "ser capaz de secuenciar".

Por último, en el apartado de actividades, en el segundo punto, aparece "A conitnuación", cuando entiendo que es "A continuación".

Un saludo

**Comment by latacita** [comment]
Admitida.

**Comment by latacita** [comment]
Verifica que esté todo correcto.

**Comment by erl430** [comment]
Todo correcto.
