### ISSUE TITLE
Erratas - Fase 7. Especificación de Requisitos Funcionales

### ISSUE THREAD

**Issue by erl430** [LatacitaTeaching/IngenieriaRequisitos#35]
Buenas tardes,

he encontrado algunas erratas en el enunciado de la práctica 7:

En la introducción:
- En la primera línea aparece "Durante de un proceso", entiendo que el "de" no tiene sentido ahí.
- En el segundo párrafo aparece "de los nuevas adquisiciones", donde entiendo que es "las"
- En la corrección de la especificación del caso de uso, en el número 32 aparece "no puede continuar seguir realizando acciones", supongo que sobra o continuar, o seguir.
- En este mismo apartado, en el número 33 aparece "elem(e)ntos".
- En la identificación de escenarios alternativos y excepcionales, aparece "completitud de los escenario alernativos", donde sería "escenario".

Un saludo

**Comment by latacita** [comment]
Admitidas todas.

**Comment by latacita** [comment]
Verificas cuando puedas que estén corregidas para cerrar la incidencia.

**Comment by erl430** [comment]
Todo correcto
